version: '3.8'

services:

  mimoto-service:
    container_name: 'mimoto-service'
    image: 'mosipqa/mimoto:0.15.x'
    user: root
    ports:
      - '8099:8099'
    environment:
      - container_user=mosip
      - active_profile_env=default
      - SPRING_CONFIG_NAME=mimoto
      - SPRING_CONFIG_LOCATION=/home/mosip/
    volumes:
      - ./config/mimoto-default.properties:/home/mosip/mimoto-default.properties
      - ./certs/oidckeystore.p12:/home/mosip/certs/oidckeystore.p12

  inji-web:
    container_name: 'inji-web'
    image: inji-web:local
    ports:
      - '3004:3004'
    environment:
      - DEFAULT_LANG=en
      - MIMOTO_HOST=http://localhost:3004/v1/mimoto
    volumes:
      - ./config/mimoto-default.properties:/home/mosip/mimoto-default.properties
      - ./config/mimoto-issuers-config.json:/home/mosip/mimoto-issuers-config.json
      - ./config/mimoto-trusted-verifiers.json:/home/mosip/mimoto-trusted-verifiers.json
    depends_on:
      - mimoto-service