export const PasscodePageStyles = {
  pageOverlay: "fixed inset-0 backdrop-blur-sm bg-black bg-opacity-40 flex flex-col items-center justify-center z-50 h-screen",
  container: "rounded-2xl bg-white flex flex-col items-center justify-start relative w-[90%] sm:w-[85%] md:w-[90%] h-fit overflow-y-auto shadow-iw-pin-page-container",
  contentWrapper: "flex flex-col items-center justify-start w-full mt-[180px] sm:mt-[200px] relative z-10 pb-0 sm:pb-8",
  titleContainer: "text-center space-y-5 relative w-full max-w-[500px] px-4 sm:px-0",
  title: "text-2xl-plus font-semibold text-iw-darkGrayishBlue",
  description: "text-iw-textTertiary text-lg font-normal mx-8",
  passcodeContainer: "flex flex-col bg-white sm:rounded-lg sm:shadow-iw-pin-page-container items-center z-20 w-full max-w-[500px] mt-8 mb-4 mx-auto border-t border-iw-grayishBlue mx-8 sm:my:0",
  warningTextBorder: "relative sm:hidden pin-page-warning-text-border min-w-full items-center justify-center mt-1 sm:mt-3 md:mt-5",
  warningTextContainer: "w-full items-center justify-center flex",
  warningText: "text-iw-textTertiary text-center text-sm sm:text-base px-4 sm:px-8 pt-4 sm:pt-6 max-w-[560px]",
  errorContainer: "bg-iw-pink50 w-full px-3 sm:px-5 py-3 border-t rounded-t-lg",
  errorContentWrapper: "flex items-start justify-between gap-2 max-w-[560px] mx-auto",
  errorText: "text-sm text-iw-darkRed break-words whitespace-normal",
  errorTextContainer: "flex-1 pr-2",
  closeButtonContainer: "flex-shrink-0",
  closeButton: "cursor-pointer",
  closeIcon: "min-w-[26px] min-h-[26px] mt-1.5 sm:mt-2 text-iw-darkRed",
  bottomBorder: "pin-page-warning-text-border w-full mt-2 sm:mt-3 md:mt-5",
  inputContainer: "w-full px-4 sm:px-8 py-3 sm:py-5 md:py-7 space-y-4 flex flex-col items-center",
  inputWrapper: "w-full mx-auto",
  inputScrollContainer: "overflow-x-auto",
  inputGroup: "flex justify-center gap-x-2 min-w-fit",
  confirmInputGroup: "flex justify-center gap-x-2 mt-4 min-w-fit",
  forgotPasscodeContainer: "w-full mx-auto flex justify-start",
  forgotPasscodeButton: "text-sm md:text-md font-semibold text-iw-deepVioletIndigo my-0 cursor-pointer",
  buttonContainer: "w-full mx-auto",
  disabledButton: "grayscale"
};