name: inji-web build upon a push

on:
  release:
    types: [ published ]
  pull_request:
    types: [ opened, reopened, synchronize ]
  push:
    branches:
      - '!release-branch'
      - release*
      - master
      - 1.*
      - develop
      - qa-develop
      - MOSIP*
      - injiweb*

jobs:
  build-dockers-inji-web:
    strategy:
      matrix:
        include:
          - SERVICE_LOCATION: "inji-web"
            SERVICE_NAME: "inji-web"
      fail-fast: false
    name: ${{ matrix.SERVICE_NAME }}
    uses: mosip/kattu/.github/workflows/docker-build.yml@master
    with:
      SERVICE_LOCATION: ${{ matrix.SERVICE_LOCATION }}
      SERVICE_NAME: ${{ matrix.SERVICE_NAME }}
    secrets:
      DEV_NAMESPACE_DOCKER_HUB: ${{ secrets.DEV_NAMESPACE_DOCKER_HUB }}
      ACTOR_DOCKER_HUB: ${{ secrets.ACTOR_DOCKER_HUB }}
      RELEASE_DOCKER_HUB: ${{ secrets.RELEASE_DOCKER_HUB }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

  sonar-analysis-inji-web:
    if: "${{  github.event_name != 'pull_request' }}"
    needs: build-dockers-inji-web
    uses: mosip/kattu/.github/workflows/npm-sonar-analysis.yml@master-java21
    with:
      SERVICE_LOCATION: ./inji-web
      SONAR_URL: 'https://sonarcloud.io'
      PROJECT_KEY: 'mosip_inji-web'
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      ORG_KEY: ${{ secrets.ORG_KEY }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

  call-trivy-scan:
    uses: mosip/kattu/.github/workflows/trivy.yml@develop
    with:
            service_name: 'inji-web'
            service_location: 'inji-web'
            version: 'latest'
